### ISSUE TITLE
Support generation of descriptors for modules with invalid auto module name

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/moditect#37]
If no valid module name can be derived from the JAR name (e.g. for _netty-transport-native-epoll-4.1.15.Final.jar_, due to the "native"), the _jdeps_ invocation fails. We can work around it by injecting a valid auto module name into the MANIFEST.

**Comment by rjpfonseca** [comment]
Hello. Your project is amazing! Aside from helping project owners to update their code with generated module descriptors, I specially like it because it also provides a way to patch third-party projects (until they add their own module descriptors).

This issue addresses a very infuriating problem which prevents us from smoothly patching some projects that have a jar file with a strange name that cannot be used to derive the module name. One example is "log4j-core" (2.10.0), which contains the dependency "jboss-jms-api_1.1_spec" with the problematic jar name.

Aside from your idea of injecting a valid automatic module name into the MANIFEST, I think an alternative/additional elegant solution would be to allow adding a declared module configuration to each dependency in the "additionalDependencies" option of the "generate-module-info" goal.

I checked your code, and you seem to be adding the descriptors of additional dependencies to a Set that is initially populated with the descriptors of resolved dependencies, which means it is possible to overwrite the resolved dependencies with additional ones. As it stands right now, only the descriptors themselves can be overwritten and this has no utility, but new code development could start from there by e.g. pairing each dependency descriptor with an optional module descriptor that would be used instead of the default one during the generation phase.

Do you think this is a sensible strategy? Were you, perhaps, already on this path? I am willing to help you implementing this but would like to coordinate with you beforehand in order to avoid redundant effort.

**Comment by gunnarmorling** [comment]
Hey, thanks a lot for your very encouraging feedback!

Indeed has the addition of descriptors to external JARs been my original motivation for this tooling (as automatic modules don't work for modular runtime images), although I'd assume that usefulness of this feature will diminish over time, as more and more project add their own descriptor. For that I still consider the help offered by ModiTect quite important, as e.g. maintaining long lists of exported packages without any wildcard support just isn't feasible IMO.

> I think an alternative/additional elegant solution would be to allow adding a declared module configuration to each dependency in the "additionalDependencies" option of the "generate-module-info" goal.

I just pushed two commits which should address the issue. The first (for this issue, #37) implements the suggested injection of the `Automatic-Module-Name` header, allowing to add descriptors to dependencies to artifacts such as _jboss-jms-api_1.1_spec_.

The second commit (for issue #38) checks whether a given `<additionalDependencies>` entry is amongst the already modularized artifacts and if so feeds the modularized JAR to the underlying invocation of _jdeps_ (instead of the non-modular original file). I.e. the following configuration should work now:

```xml
<plugin>
    <groupId>org.moditect</groupId>
    <artifactId>moditect-maven-plugin</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <executions>
        <execution>
            <id>add-module-info-to-dependencies</id>
            <phase>package</phase>
            <configuration>
                <outputDirectory>${project.build.directory}/modules</outputDirectory>
                <modules>
                    <module>
                        <artifact>
                            <groupId>org.jboss.spec.javax.jms</groupId>
                            <artifactId>jboss-jms-api_1.1_spec</artifactId>
                        </artifact>
                        <moduleInfo>
                            <name>java.jms</name>
                        </moduleInfo>
                    </module>
                    <module>
                        <artifact>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-core</artifactId>
                        </artifact>
                        <moduleInfo>
                            <name>org.apache.logging.log4j.core</name>
                        </moduleInfo>
                    </module>
                    ...
```

The descriptor generated for and added to log4j should contain a dependence to `java.jms` that way.

Could you try and build ModiTect from master yourself (just run `mvn clean install`) and let me know whether this works for you? Note you can omit the versions of the artifacts to be modularized of they are listed as a dependency or within the dependency management of your project.

Thanks again for your feedback and input, that's much appreciated! If you got anything else, please let me know.

**Comment by rjpfonseca** [comment]
I'm getting a NullPointerException when I use my attached pom. It's a minimalist example just to get a hold of things. The module-info of java.jms is generated but the execution aborts with the exception and the module-info for log4j-core is not generated.

[pom.zip](https://github.com/moditect/moditect/files/1608415/pom.zip)

I run this with 'mvn clean package'.

Am I forgetting something in my configuration, which is triggering the exception due to being an unexpected scenario? Of course, the exception should never occur in the first place, but maybe my problem is that I'm not doing something right in the first place. Do you see the problem?

Thanks for your help!

**Comment by rjpfonseca** [comment]
OK, I found the problem I was having. If I don't define a dependency management in my pom, then your plugin throws an exception because it is assuming that a dependency management is always present. So to fix my problem I just have to define one.

However, I was also thinking how best to fix the NullPointerException problem in your plugin. In your code, there are two places where you are retrieving the dependency management from the project object: [ModuleInfoGenerator](https://github.com/moditect/moditect/blob/7f210838714856b2ee5cec1889e32ba535c26fb5/maven-plugin/src/main/java/org/moditect/mavenplugin/generate/ModuleInfoGenerator.java#L207) and [AddModuleInfoMojo](https://github.com/moditect/moditect/blob/7f210838714856b2ee5cec1889e32ba535c26fb5/maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java#L205l). I'm not familiar with maven plugin development and its current best practices, and I couldn't find anything online on what's the appropriate way to get all of a project's direct dependencies. Should one get all the dependencies from MavenProject::getDependencies and then somehow combine those with any present via MavenProject::getDependencyManagement in case it exists? Maybe there's no general guidance and it depends on what a plugin wants to do. What do you think could be done in your case?

**Comment by gunnarmorling** [comment]
> OK, I found the problem I was having. If I don't define a dependency management in my pom, then your plugin throws an exception because it is assuming that a dependency management is always present. So to fix my problem I just have to define one.

Ah, I see. It definitely should work without the DM block, good catch!

>  What do you think could be done in your case?

I think the simplest would be to just guard against null in the two locations you've identified. Aether (the library Maven and this plug-in are using to resolve dependencies), also optionally accepts DM information when being asked to resolve a dependency, so in theory we could pass it there instead of handling DM ourselves. But then we still need to check the actual project dependencies whether a an artifact to be modularized is present there (so its version doesn't have to be repeated in the ModiTect plug-in config), so it's probably easier to just stick to the current approach. Open for suggestions :)

**Comment by gunnarmorling** [comment]
So I'm going to close this one then as it seems resolved. Thanks for opening #40 for the NPE, let's continue the discussion of that issue over there then.
